server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gpus_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false

agrgtr:
  cron: 0 0 0 * * * #каждый день в полночь

logging:
  file:
    name: src/main/resources/application-debug.log
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  level:
    org:
      springframework:
        web: TRACE

technopark:
  name: Technopark
  url:
    list: https://www.technopark.ru/videokarty/?p=%d
    base: https://www.technopark.ru/
    product: https://www.technopark.ru/graphql/