server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/gpus_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  level:
    root: info
    org:
      hibernate:
      springframework: info

technopark:
  name: Technopark
  url:
    list: https://www.technopark.ru/videokarty/?p=%d
    base: https://www.technopark.ru/
    product: https://www.technopark.ru/graphql/

dns:
  name: DNS Store
  url:
    list:  https://www.dns-shop.ru/catalog/17a89aab16404e77/videokarty/?p=%d
    base:  https://www.dns-shop.ru/
    product: https://www.dns-shop.ru/product/
