server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gpus_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
    database:
    hibernate:
      ddl-auto: create
  properties:
    hibernate:
      format_sql: true

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

url:
  technopark:
    list: https://www.technopark.ru/videokarty/?p=%d
    base: https://www.technopark.ru/
    product: https://www.technopark.ru/graphql/
  mvideo:
  citilink:
  dns:
