server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gpus_db
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    open-in-view: false
  properties:
    hibernate:
      format_sql: true

url:
  technopark:
    list: https://www.technopark.ru/videokarty/?p=%d
    base: https://www.technopark.ru/
    one-videocard: https://www.technopark.ru/graphql/